# See full spec at https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: artifactory-test
  namespace: argocd # the namespace of the ArgoCD deployment itself
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true

  source:
    chart: 'artifactory'
    repoURL: 'https://charts.jfrog.io/'
    targetRevision: 107.27.9
    helm:
      #### Artifactory values.yaml ####
      values: |
        artifactory:
          joinKey: 011b61f5c6a5928d4489df5fe6f120569c29c9e9dafb01f720c61853a3d90e2b
          masterKey: ce2dcb873c3094d5dd8e7a7136158e4f31866d802435306c1855a7213853ee34
          replicaCount: 2

        databaseUpgradeReady: true
        unifiedUpgradeAllowed: true

        postgresql:
          postgresqlPassword: password

