apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xray-test
  namespace: argocd # the namespace of the ArgoCD deployment itself
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true

  source:
    chart: 'xray'
    repoURL: 'https://charts.jfrog.io/'
    targetRevision: 103.37.2
    helm:
      #### Artifactory values.yaml ####
      values: |
        rabbitmq:
          auth:
            password: f4PeLNdq25
        postgresql:
          postgresqlPassword: password
        xray:
          joinKey: 011b61f5c6a5928d4489df5fe6f120569c29c9e9dafb01f720c61853a3d90e2b
          masterKey: b46337c2a998d931246535fd2826928b83e3fb29bc4e5c8972c7c8e23f919b7c
          jfrogUrl: http://artifactory-test:8082
        unifiedUpgradeAllowed: true
        databaseUpgradeReady: true

