apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: couchbase-test
  namespace: argocd # the namespace of the ArgoCD deployment itself
spec:
  project: default
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true

  source:
    chart: 'couchbase/couchbase-operator'
    repoURL: 'https://couchbase-partners.github.io/helm-charts/'
    # targetRevision: 107.27.9
    helm:
      #### values.yaml ####
      values: |
        cluster:
          name: 'My Couchbase Cluster'